name: Daily CI

on:
  schedule:
    - cron: '0 1 * * *'

  workflow_dispatch:

  pull_request:

  push:
    branches: [main]

jobs:
  daily-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: pnpm install

      - name: Build Rspack
        run: |
          pnpm build:rspack

      - name: Build Rsbuild
        run: |
          pnpm build:rsbuild

      - name: Build Rspress
        run: |
          pnpm build:pspress

      - name: Build Rsdoctor
        run: |
          pnpm build:rsdoctor
